[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling>=1.27", # PEP 639 license expressions
]

[project]
name = "plantranger"
description = "Asynchronous client for the Plant Ranger API"
readme = "README.md"
keywords = [
    "asyncio",
    "homeassistant",
    "plantranger",
]
license = "Apache-2.0"
license-files = [
    "LICENSE",
]
authors = [
    { name = "Digital Buttes LLC" },
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
]
dynamic = [
    "version",
]
dependencies = [
    "aiohttp>=3.9",
]

[project.urls]
Changelog = "https://github.com/digitalbuttesorg/python-plantranger/blob/main/CHANGELOG.md"
Homepage = "https://github.com/digitalbuttesorg/python-plantranger"
Issues = "https://github.com/digitalbuttesorg/python-plantranger/issues"
Source = "https://github.com/digitalbuttesorg/python-plantranger"

[tool.hatch.version]
path = "plantranger/__init__.py"

[tool.hatch.build.targets.wheel]
packages = [
    "plantranger",
]

[tool.hatch.build.targets.sdist]
include = [
    "/plantranger",
    "/README.md",
    "/LICENSE",
    "/CHANGELOG.md",
]

[tool.ruff]
target-version = "py312"
